language: python
python:
    - 3.8
    - 3.7
    - 3.6
    - 3.5
    - 3.4
    - 2.7

install: pip install coveralls
script: make ci
after_success: coveralls

branches:
    only:
        - master
notifications:
    email:
        on_success: never
        on_failure: change
